sonar.projectKey=ecommerce-project
sonar.projectName=ecommerce-project
sonar.projectVersion=1.0

sonar.sources=.

sonar.exclusions=node_modules/**,coverage/**,dist/**,build/**

sonar.sourceEncoding=UTF-8