### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

###

### GET request to findAll Product
GET http://localhost:8082/api/v1/products

###

POST http://localhost:8082/api/v1/products
Content-Type: application/json

{
  "name": "Nike Air Max",
  "description": "Running shoes",
  "price": 120.99,
  "imageUrl": "https://example.com/shoe.jpg",
  "category": "Shoes",
  "quantity": 5
}