### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

###

### GET request to findAll Product
GET http://localhost:8082/api/v1/products

###

POST http://localhost:8082/api/v1/products
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJoMjM0NTEiLCJpYXQiOjE3NDg2MzI1NzcsImV4cCI6MTc0ODYzNjE3N30.wxuPYmOMfXP2S_i435joHTFbIpM5WBqDtca3ENw3Ko8
Content-Type: application/json

{
  "name": "Test Product",
  "description": "A great product",
  "price": 99.99,
  "imageUrl": "https://via.placeholder.com/150",
  "category": "electronics",
  "quantity": 5
}

###

GET http://localhost:8082/api/v1/products/2


###
PUT http://localhost:8082/api/v1/products/2
Content-Type: application/json

{
  "name": "Herin",
  "description": "Now with RGB lighting",
  "price": 24.99,
  "imageUrl": "https://via.placeholder.com/150",
  "category": "electronics",
  "quantity": 8
}

###
DELETE http://localhost:8082/api/v1/products/6

### User

## Register

POST http://localhost:8082/api/v1/auth/register
Content-Type: application/json


{
  "username": "a3",
  "email": "bademail22@gmail.com",
  "password": "123@patLe"
}



###Login

POST http://localhost:8082/api/v1/auth/login
Content-Type: application/json

{
"identifier": "h23451",
"password": "StrongPass@123"
}

###Cart
GET http://localhost:8082/api/v1/cart
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJoMjM0NTEiLCJpYXQiOjE3NDg4Nzk3NjAsImV4cCI6MTc0ODg4MzM2MH0.mpEI4XLYRuVVff3Cf2KWe-86jP70Zg3bQOyxB1KoviA


### Add item to cartqa
POST http://localhost:8082/api/v1/cart/add
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJoMjM0NTEiLCJpYXQiOjE3NDg4Nzk3NjAsImV4cCI6MTc0ODg4MzM2MH0.mpEI4XLYRuVVff3Cf2KWe-86jP70Zg3bQOyxB1KoviA
Content-Type: application/json

{
  "productId": 23,
  "quantity": 6
}




