name: SonarQube Scan

on:
  push:
    branches:
      #- '**'
      - 'ABDOU'

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        working-directory: ./frontend
        run: npm install

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@master
        with:
            projectBaseDir: frontend
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}